In [2]:
# Import necessary libraries
import sys
import os

# Add the directory containing the script to sys.path
sys.path.append(os.path.abspath('../src'))  # Adjust the path to point to the directory containing fraud_detection.py

# Import the function from the script
from fraud_detection import run_fraud_detection

# Call the function with the path to your dataset
run_fraud_detection('../data/fraud_cleaned.csv')

Fraud Class Distribution:
 class
0    0.906354
1    0.093646
Name: proportion, dtype: float64

Training Logistic Regression...


D:\10Academy1\fraud_detection\week-8\Lib\site-packages\sklearn\impute\_base.py:635: UserWarning: Skipping features without any observed values: ['ip_int']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
D:\10Academy1\fraud_detection\week-8\Lib\site-packages\sklearn\impute\_base.py:635: UserWarning: Skipping features without any observed values: ['ip_int']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
D:\10Academy1\fraud_detection\week-8\Lib\site-packages\sklearn\impute\_base.py:635: UserWarning: Skipping features without any observed values: ['ip_int']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(



📊 Logistic Regression Results:
[[34084   156]
 [ 2192  1346]]
              precision    recall  f1-score   support

           0       0.94      1.00      0.97     34240
           1       0.90      0.38      0.53      3538

    accuracy                           0.94     37778
   macro avg       0.92      0.69      0.75     37778
weighted avg       0.94      0.94      0.93     37778

F1 Score: 0.5341269841269841
Average Precision (AUC-PR): 0.5812689702978775


D:\10Academy1\fraud_detection\week-8\Lib\site-packages\sklearn\impute\_base.py:635: UserWarning: Skipping features without any observed values: ['ip_int']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
D:\10Academy1\fraud_detection\week-8\Lib\site-packages\sklearn\impute\_base.py:635: UserWarning: Skipping features without any observed values: ['ip_int']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(



Training XGBoost...

📊 XGBoost Results:
[[30351  3889]
 [ 2166  1372]]
              precision    recall  f1-score   support

           0       0.93      0.89      0.91     34240
           1       0.26      0.39      0.31      3538

    accuracy                           0.84     37778
   macro avg       0.60      0.64      0.61     37778
weighted avg       0.87      0.84      0.85     37778

F1 Score: 0.3118536197295147
Average Precision (AUC-PR): 0.3210012772678157

📌 Model Comparison:
Logistic Regression → F1: 0.5341, AUC-PR: 0.5813
XGBoost             → F1: 0.3119, AUC-PR: 0.3210

🏆 Logistic Regression outperforms XGBoost on F1 and AUC-PR metrics.


In [18]:
# Import necessary libraries
import sys
import os

# Add the directory containing the script to sys.path
sys.path.append(os.path.abspath('../src'))  # Adjust the path to your script directory

# Import the function from the script
from data_preparation import run_fraud_detection

# Define paths
data_path = '../data/fraud_cleaned.csv'  # Adjust according to your data location
model_dir = 'D:/10Academy1/fraud_detection/models'  # Adjust as needed

# Call the function
run_fraud_detection(data_path, model_dir)

D:\10Academy1\fraud_detection\week-8\Lib\site-packages\sklearn\impute\_base.py:635: UserWarning: Skipping features without any observed values: ['ip_int']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
D:\10Academy1\fraud_detection\week-8\Lib\site-packages\sklearn\impute\_base.py:635: UserWarning: Skipping features without any observed values: ['ip_int']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(


Training Logistic Regression...
Logistic Regression Results:
[[26964   429]
 [ 1249  1581]]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97     27393
           1       0.79      0.56      0.65      2830

    accuracy                           0.94     30223
   macro avg       0.87      0.77      0.81     30223
weighted avg       0.94      0.94      0.94     30223

F1 Score: 0.653305785123967
Average Precision (AUC-PR): 0.5745924264311452
Training XGBoost...
XGBoost Results:
[[24039  3354]
 [ 1740  1090]]
              precision    recall  f1-score   support

           0       0.93      0.88      0.90     27393
           1       0.25      0.39      0.30      2830

    accuracy                           0.83     30223
   macro avg       0.59      0.63      0.60     30223
weighted avg       0.87      0.83      0.85     30223

F1 Score: 0.2996975529282376
Average Precision (AUC-PR): 0.330638243855421

Model Comparison:
Logistic Regressi

In [19]:
# Import necessary libraries
import sys
import os

# Add the directory containing the script to sys.path
sys.path.append(os.path.abspath('../src'))  # Adjust the path to your script directory

# Import the function from the script
from models_taining import run_fraud_detection

# Call the function with the path to your dataset
data_path = '../data/creditcard.csv'  # Adjust according to your data location
run_fraud_detection(data_path)

Class distribution:
 Class
0    0.998273
1    0.001727
Name: proportion, dtype: float64

🔹 Logistic Regression Results:
[[69444  1635]
 [   14   109]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     71079
           1       0.06      0.89      0.12       123

    accuracy                           0.98     71202
   macro avg       0.53      0.93      0.55     71202
weighted avg       1.00      0.98      0.99     71202

F1 Score: 0.11676486341724691
Average Precision (AUC-PR): 0.7038566346457426

🔹 XGBoost Results:
[[70894   185]
 [   18   105]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     71079
           1       0.36      0.85      0.51       123

    accuracy                           1.00     71202
   macro avg       0.68      0.93      0.75     71202
weighted avg       1.00      1.00      1.00     71202

F1 Score: 0.5084745762711864
Average Precision (AUC-PR): 0.80405731

In [7]:
# Import necessary libraries
import sys
import os

# Add the directory containing the script to sys.path
sys.path.append(os.path.abspath('../src'))  # Adjust the path to your script directory

# Import the function from the script
from model_evaluation import run_fraud_detection

# Define paths
data_path = '../data/creditcard.csv'  # Adjust according to your data location
model_save_path = '../models'  # Adjust as needed

# Call the function
run_fraud_detection(data_path, model_save_path)

Training Logistic Regression...

Logistic Regression Results:
[[55397  1467]
 [    8    90]]
              precision    recall  f1-score   support

           0       1.00      0.97      0.99     56864
           1       0.06      0.92      0.11        98

    accuracy                           0.97     56962
   macro avg       0.53      0.95      0.55     56962
weighted avg       1.00      0.97      0.99     56962

F1 Score: 0.10876132930513595
Average Precision (AUC-PR): 0.724469435669471

Starting XGBoost hyperparameter tuning...

Best XGBoost params: {'objective': 'binary:logistic', 'eval_metric': 'aucpr', 'scale_pos_weight': np.float64(1.0), 'seed': 42, 'max_depth': 6, 'eta': 0.1, 'subsample': 0.8, 'colsample_bytree': 1, 'verbosity': 0}
Best XGBoost F1 at threshold 0.5: 0.5260
Optimal threshold based on max F1: 0.9809

XGBoost Results with tuned threshold:
[[56858     6]
 [   20    78]]
              precision    recall  f1-score   support

           0       1.00      1.00      1

In [20]:
# Example for XGBoost
import matplotlib.pyplot as plt
from xgboost import plot_importance

plot_importance(xgb_model, max_num_features=10)
plt.title("XGBoost Feature Importance")
plt.show()

NameError: name 'xgb_model' is not defined